(function () {
  const targets = {
    nouns: 140,
    adverbs: 160,
    verbs: 150,
    'sentence-parts': 110,
    verbals: 90,
    pronouns: 80,
    sentences: 90,
    clauses: 80,
    prepositions: 50,
    adjectives: 30,
    conjunctions: 20
  };

  const singularActors = [
    'the city council', 'the university', 'the research team', 'the hospital', 'the company',
    'the government', 'the school district', 'the transport agency', 'the environmental group',
    'the charity', 'the museum', 'the employer', 'the housing department', 'the technology firm',
    'the public library', 'the committee', 'the tourism board', 'the local community',
    'the health service', 'the planning office'
  ];

  const pluralActors = [
    'researchers', 'commuters', 'students', 'residents', 'parents', 'employees', 'tourists',
    'volunteers', 'policymakers', 'scientists', 'consumers', 'drivers', 'teachers', 'nurses',
    'workers', 'farmers', 'graduates', 'teenagers', 'households', 'local businesses'
  ];

  const topics = [
    'air quality', 'public transport', 'online learning', 'housing costs', 'renewable energy',
    'water use', 'job satisfaction', 'road safety', 'migration patterns', 'health services',
    'urban noise', 'food waste', 'digital privacy', 'childcare provision', 'tourism growth',
    'public spending', 'remote work', 'student wellbeing', 'recycling rates', 'green spaces'
  ];

  const policyObjects = [
    'access to healthcare', 'public transport', 'waste collection', 'energy efficiency',
    'student support', 'water quality', 'road safety', 'online learning', 'housing supply',
    'air quality', 'digital access', 'childcare services', 'recycling facilities',
    'employment prospects', 'community safety', 'public parks', 'hospital capacity',
    'tourist information', 'library services', 'mental health support'
  ];

  const changes = [
    'improved', 'expanded', 'reduced', 'monitored', 'reviewed', 'introduced', 'funded',
    'measured', 'protected', 'upgraded', 'simplified', 'strengthened', 'evaluated',
    'supported', 'modernised', 'regulated', 'increased', 'limited', 'redesigned', 'tested'
  ];

  const pastActions = [
    'collected the data', 'reviewed the evidence', 'completed the survey', 'interviewed the residents',
    'analysed the figures', 'published the report', 'checked the results', 'revised the proposal',
    'tested the equipment', 'consulted local businesses', 'updated the guidelines', 'measured the impact',
    'prepared the questionnaire', 'approved the budget', 'inspected the building'
  ];

  const dates = [
    '1 January 2024', '15 March 2023', '22 June 2022', '9 September 2021', '3 April 2020',
    '18 November 2019', '6 February 2018', '27 July 2017', '12 May 2016', '30 October 2015'
  ];

  const years = ['2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024'];
  const months = ['January', 'March', 'April', 'June', 'August', 'September', 'October', 'November'];
  const times = ['8 a.m.', 'noon', '6 p.m.', 'midnight', 'the weekend'];

  const pick = (items, index, offset = 0) => items[(index + offset) % items.length];
  const cap = (text) => text.charAt(0).toUpperCase() + text.slice(1);

  function makeOptions(correct, distractors, seed) {
    const unique = [];
    [correct, ...distractors].forEach((option) => {
      if (!unique.includes(option)) unique.push(option);
    });
    const base = unique.slice(0, 4);
    const shift = seed % base.length;
    const options = base.slice(shift).concat(base.slice(0, shift));
    return { options, answer: options.indexOf(correct) };
  }

  function item(id, category, type, errorType, prompt, correct, distractors, rule, explanation, seed) {
    const { options, answer } = makeOptions(correct, distractors, seed);
    return { id, category, type, errorType, prompt, options, answer, rule, explanation };
  }

  const templates = {
    nouns: [
      (i, id) => item(id, 'nouns', 'Complète la phrase', 'Nom indénombrable',
        `The survey provides useful ___ about ${pick(topics, i)}.`,
        'information', ['informations', 'an information', 'many information'],
        'Information est indénombrable',
        'En anglais, “information” ne prend pas de -s et ne s’utilise pas avec “an”. Écris “some information” ou “a piece of information”.', i),
      (i, id) => item(id, 'nouns', 'Complète la phrase', 'Nom indénombrable',
        `${cap(pick(singularActors, i))} gave ${pick(pluralActors, i)} practical ___ before the change.`,
        'advice', ['advices', 'an advice', 'many advice'],
        'Advice est indénombrable',
        '“Advice” fonctionne comme “information” : pas de pluriel direct. Pour compter, écris “pieces of advice”.', i),
      (i, id) => item(id, 'nouns', 'Choisis le déterminant', 'Quantité',
        `Only ___ equipment was needed for the ${pick(topics, i)} project.`,
        'a little', ['a few', 'many', 'several'],
        'Equipment est indénombrable',
        '“Equipment” ne se compte pas directement. “A little equipment” est naturel ; “many equipments” est une erreur fréquente.', i),
      (i, id) => item(id, 'nouns', 'Corrige la phrase', 'Nombre',
        `Choose the best correction: “${cap(pick(singularActors, i))} conducted many researches into ${pick(topics, i)}.”`,
        `${cap(pick(singularActors, i))} conducted a great deal of research into ${pick(topics, i)}.`,
        [`${cap(pick(singularActors, i))} conducted many researches into ${pick(topics, i)}.`, `${cap(pick(singularActors, i))} conducted a research into ${pick(topics, i)}.`, `${cap(pick(singularActors, i))} conducted several research into ${pick(topics, i)}.`],
        'Research est souvent indénombrable',
        'Dans ce sens, “research” est indénombrable : “a great deal of research”, “some research” ou “research studies”.', i),
      (i, id) => item(id, 'nouns', 'Complète la phrase', 'Quantité',
        `The report contains ___ evidence that ${pick(policyObjects, i)} has improved.`,
        'strong', ['many', 'several', 'an'],
        'Evidence est indénombrable',
        '“Evidence” ne prend pas “many” ou “several” dans ce sens. On peut dire “strong evidence” ou “pieces of evidence”.', i),
      (i, id) => item(id, 'nouns', 'Choisis la forme correcte', 'Quantité',
        `${cap(pick(pluralActors, i))} reported ___ traffic after the new route opened.`,
        'less', ['fewer', 'many', 'a few'],
        'Less avec un indénombrable',
        '“Traffic” est traité comme une masse. On dit “less traffic”, pas “fewer traffic”.', i),
      (i, id) => item(id, 'nouns', 'Complète la phrase', 'Nom indénombrable',
        `Finding affordable ___ near ${pick(['campus', 'the hospital', 'the city centre', 'the station', 'the business district', 'the coast', 'the main library', 'the research park', 'the airport', 'the old town', 'the university', 'the training centre', 'the industrial zone', 'the new metro line'], i)} remains difficult for many students.`,
        'accommodation', ['accommodations', 'an accommodation', 'many accommodation'],
        'Accommodation est généralement indénombrable',
        'En anglais britannique IELTS, “accommodation” est normalement indénombrable quand on parle de logement en général.', i),
      (i, id) => item(id, 'nouns', 'Choisis le bon nom', 'Nom indénombrable',
        `${cap(pick(singularActors, i))} bought new ___ for the study area.`,
        'furniture', ['furnitures', 'a furniture', 'many furniture'],
        'Furniture est indénombrable',
        'On dit “furniture” ou “pieces of furniture”, mais pas “furnitures”.', i),
      (i, id) => item(id, 'nouns', 'Choisis le possessif', 'Possessif',
        `The ___ ${pick(['results', 'attendance', 'reading scores', 'confidence', 'participation', 'progress', 'wellbeing', 'performance', 'motivation', 'behaviour', 'language skills', 'test scores', 'classroom experience', 'writing accuracy'], i)} improved after extra support was introduced.`,
        "children's", ["childrens'", 'childrens', "children"],
        'Pluriel irrégulier + possessif',
        '“Children” est déjà pluriel. Le possessif se forme avec ’s : “children’s results”.', i),
      (i, id) => item(id, 'nouns', 'Corrige la phrase', 'Nombre',
        `Choose the best correction: “The news about ${pick(topics, i)} are encouraging.”`,
        `The news about ${pick(topics, i)} is encouraging.`,
        [`The news about ${pick(topics, i)} are encouraging.`, `The news about ${pick(topics, i)} have encouraging.`, `The news about ${pick(topics, i)} were encourage.`],
        'News est singulier',
        'Même avec un -s final, “news” prend normalement un verbe singulier : “the news is”.', i)
    ],

    adverbs: [
      (i, id) => item(id, 'adverbs', 'Complète la phrase', 'Adverbe',
        `${cap(pick(policyObjects, i))} improved ___ after the investment.`,
        'rapidly', ['rapid', 'rapidity', 'more rapid'],
        'Un verbe demande souvent un adverbe',
        'Ici, le mot décrit comment la situation a changé. Il faut l’adverbe “rapidly”.', i),
      (i, id) => item(id, 'adverbs', 'Corrige l’ordre', 'Ordre',
        `Choose the best correction: “${cap(pick(singularActors, i))} has improved significantly ${pick(policyObjects, i)}.”`,
        `${cap(pick(singularActors, i))} has significantly improved ${pick(policyObjects, i)}.`,
        [`${cap(pick(singularActors, i))} has improved significantly ${pick(policyObjects, i)}.`, `${cap(pick(singularActors, i))} significantly has improved ${pick(policyObjects, i)}.`, `Significantly ${pick(singularActors, i)} has improved ${pick(policyObjects, i)}.`],
        'Position médiane de l’adverbe',
        'Avec “has + participe passé”, l’adverbe se place souvent entre l’auxiliaire et le verbe : “has significantly improved”.', i),
      (i, id) => item(id, 'adverbs', 'Choisis la forme', 'Adjectif ou adverbe',
        `The evidence about ${pick(topics, i)} appears ___ in this section of the report.`,
        'strong', ['strongly', 'strength', 'more strongly'],
        'Après appear, adjectif',
        '“Appears” relie le sujet à une qualité. On décrit “the evidence”, donc on utilise l’adjectif “strong”.', i),
      (i, id) => item(id, 'adverbs', 'Choisis le bon mot', 'Faux ami',
        `${cap(pick(pluralActors, i))} worked ___ to finish the project on time.`,
        'hard', ['hardly', 'hardly hard', 'more hardly'],
        'Hard ≠ hardly',
        '“Work hard” signifie travailler dur. “Hardly” signifie “à peine”, donc presque le contraire.', i),
      (i, id) => item(id, 'adverbs', 'Complète la phrase', 'Degré',
        `The two estimates for ${pick(policyObjects, i)} were ___ identical, with a difference of less than 0.1%.`,
        'nearly', ['hardly', 'highly', 'deeply'],
        'Nearly = presque',
        '“Nearly identical” signifie presque identiques. “Hardly identical” signifierait presque pas identiques.', i),
      (i, id) => item(id, 'adverbs', 'Choisis la forme', 'Adjectif ou adverbe',
        `${cap(pick(pluralActors, i))} performed ___ during the final trial.`,
        'well', ['good', 'betterly', 'more good'],
        'Good décrit un nom, well décrit souvent une action',
        'Ici, le mot décrit la manière dont ils ont performé : “performed well”.', i),
      (i, id) => item(id, 'adverbs', 'Évite l’erreur', 'Forme',
        `The number of complaints about ${pick(policyObjects, i)} fell ___ after the new system was introduced.`,
        'fast', ['fastly', 'more fast', 'fastness'],
        'Fast peut être adjectif ou adverbe',
        '“Fast” est déjà un adverbe correct. “Fastly” n’est pas naturel en anglais standard.', i),
      (i, id) => item(id, 'adverbs', 'Choisis le sens', 'Faux ami',
        `${cap(pick(pluralActors, i))} arrived ___ because the train was delayed.`,
        'late', ['lately', 'latest', 'laterly'],
        'Late ≠ lately',
        '“Late” signifie en retard. “Lately” signifie récemment.', i),
      (i, id) => item(id, 'adverbs', 'Complète la phrase', 'Degré',
        `It is ___ unlikely that the figures for ${pick(topics, i)} will change dramatically.`,
        'highly', ['high', 'height', 'higher'],
        'Highly + adjectif',
        'Pour renforcer un adjectif comme “unlikely”, on utilise l’adverbe “highly”.', i),
      (i, id) => item(id, 'adverbs', 'Corrige la phrase', 'Adverbe',
        `Choose the best correction: “${cap(pick(singularActors, i))} responded quick to the complaints.”`,
        `${cap(pick(singularActors, i))} responded quickly to the complaints.`,
        [`${cap(pick(singularActors, i))} responded quick to the complaints.`, `${cap(pick(singularActors, i))} responded quicker to the complaints.`, `${cap(pick(singularActors, i))} responded quickness to the complaints.`],
        'Quickly modifie un verbe',
        '“Responded” est une action. Pour dire comment elle a été faite, on utilise “quickly”.', i)
    ],

    verbs: [
      (i, id) => item(id, 'verbs', 'Choisis le temps', 'Temps',
        `Since ${pick(years, i)}, ${pick(singularActors, i)} ___ ${pick(policyObjects, i)}.`,
        `has ${pick(changes, i)}`, [`${pick(changes, i)}`, `had ${pick(changes, i)}`, `is ${pick(changes, i)}`],
        'Since → present perfect',
        '“Since + point de départ” relie le passé au présent. On utilise souvent “has/have + participe passé”.', i),
      (i, id) => item(id, 'verbs', 'Choisis le temps', 'Temps',
        `By the time the meeting began, ${pick(pluralActors, i)} ___ .`,
        `had ${pick(pastActions, i)}`, [`have ${pick(pastActions, i)}`, `${pick(pastActions, i)}`, `were ${pick(pastActions, i)}`],
        'By the time → past perfect',
        'Une action terminée avant une autre action passée prend “had + participe passé”.', i),
      (i, id) => item(id, 'verbs', 'Complète au passif', 'Voix',
        `The final report on ${pick(topics, i)} ___ by an independent panel next week.`,
        'will be reviewed', ['will review', 'is reviewing', 'has reviewed'],
        'Passif au futur',
        'Le rapport reçoit l’action. On écrit “will be + participe passé”.', i),
      (i, id) => item(id, 'verbs', 'Accorde le verbe', 'Accord',
        `The number of ${pick(pluralActors, i)} ___ every year.`,
        'increases', ['increase', 'are increasing', 'have increase'],
        'The number of → singulier',
        'Le noyau du sujet est “number”, singulier. “A number of” serait différent.', i),
      (i, id) => item(id, 'verbs', 'Accorde le verbe', 'Accord',
        `A number of ${pick(pluralActors, i)} ___ concerned about ${pick(topics, i)}.`,
        'are', ['is', 'was', 'has'],
        'A number of → pluriel',
        '“A number of people/students/residents” signifie plusieurs personnes : le verbe est pluriel.', i),
      (i, id) => item(id, 'verbs', 'Choisis la condition', 'Temps',
        `If ${pick(singularActors, i)} invests now, future costs ___ lower.`,
        'will be', ['would be', 'are being', 'had been'],
        'Condition réelle',
        'Dans une condition réelle : “If + présent, will + base verbale”.', i),
      (i, id) => item(id, 'verbs', 'Complète la phrase', 'Habitude passée',
        `${cap(pick(pluralActors, i))} ___ paper forms before the online system was introduced.`,
        'used to complete', ['were used to complete', 'use to completing', 'used completing'],
        'Used to + base verbale',
        '“Used to” décrit une habitude passée qui n’est plus vraie maintenant.', i),
      (i, id) => item(id, 'verbs', 'Choisis le modal', 'Nuance',
        `The figures for ${pick(topics, i)} are provisional, so they ___ change after the audit.`,
        'might', ['must', 'used to', 'should not'],
        'Might = possibilité',
        '“Might” exprime une possibilité incertaine. “Must” serait trop fort.', i),
      (i, id) => item(id, 'verbs', 'Corrige la phrase', 'Accord',
        `Choose the best correction: “Each of the proposals for ${pick(policyObjects, i)} have advantages.”`,
        `Each of the proposals for ${pick(policyObjects, i)} has advantages.`,
        [`Each of the proposals for ${pick(policyObjects, i)} have advantages.`, `Each of the proposals for ${pick(policyObjects, i)} are advantages.`, `Each of the proposals for ${pick(policyObjects, i)} having advantages.`],
        'Each → singulier',
        '“Each” insiste sur chaque élément séparément. Le verbe est donc singulier : “has”.', i),
      (i, id) => item(id, 'verbs', 'Choisis le temps', 'Temps',
        `For the last decade, ${pick(policyObjects, i)} ___ steadily.`,
        'has improved', ['improved', 'had improved', 'will improve'],
        'For + période jusqu’au présent',
        '“For the last decade” indique une période qui arrive jusqu’à maintenant : present perfect.', i)
    ],

    'sentence-parts': [
      (i, id) => item(id, 'sentence-parts', 'Complète la phrase', 'Structure',
        `Because ${pick(policyObjects, i)} became more affordable, ___.`,
        `${pick(pluralActors, i)} used it more often`, [`which ${pick(pluralActors, i)} used it more often`, `and ${pick(pluralActors, i)} using it more often`, `more often by ${pick(pluralActors, i)}`],
        'Because appelle une phrase complète',
        'Après la proposition en “because”, il faut une proposition principale complète.', i),
      (i, id) => item(id, 'sentence-parts', 'Corrige la phrase', 'Structure',
        `Choose the best correction: “The increase in ${pick(topics, i)} affecting many families.”`,
        `The increase in ${pick(topics, i)} is affecting many families.`,
        [`The increase in ${pick(topics, i)} affecting many families.`, `The increase in ${pick(topics, i)} it affecting many families.`, `The increase in ${pick(topics, i)} to affect many families.`],
        'Verbe conjugué principal',
        '“Affecting” seul ne porte pas le temps de la phrase. “Is affecting” corrige le fragment.', i),
      (i, id) => item(id, 'sentence-parts', 'Choisis l’accord', 'Accord',
        `The impact of changes to ${pick(policyObjects, i)} ___ difficult to measure.`,
        'is', ['are', 'were', 'have been'],
        'Le noyau commande l’accord',
        'Le noyau est “impact”, singulier. Le groupe “of these changes” ne commande pas le verbe.', i),
      (i, id) => item(id, 'sentence-parts', 'Corrige l’ordre', 'Ordre',
        `Choose the best correction: “${cap(pick(singularActors, i))} has improved significantly ${pick(policyObjects, i)}.”`,
        `${cap(pick(singularActors, i))} has significantly improved ${pick(policyObjects, i)}.`,
        [`${cap(pick(singularActors, i))} has improved significantly ${pick(policyObjects, i)}.`, `${cap(pick(singularActors, i))} significantly has improved ${pick(policyObjects, i)}.`, `${cap(pick(singularActors, i))} has improved ${pick(policyObjects, i)} significantly for.`],
        'Ordre naturel',
        'La phrase reste plus claire quand l’adverbe médian se place dans le groupe verbal.', i),
      (i, id) => item(id, 'sentence-parts', 'Évite le fragment', 'Structure',
        `Choose the complete sentence about ${pick(policyObjects, i)}.`,
        `Although ${pick(policyObjects, i)} remains expensive, demand is rising.`,
        [`Although ${pick(policyObjects, i)} remains expensive.`, `While demand is rising.`, `Because the policy changed.`, `Despite demand rising.`],
        'Une dépendante ne vit pas seule',
        '“Although/while/because” ouvre une idée dépendante. Il faut une proposition principale.', i),
      (i, id) => item(id, 'sentence-parts', 'Corrige la phrase', 'Accord',
        `Choose the best correction: “There is several reasons for the decline in ${pick(policyObjects, i)}.”`,
        `There are several reasons for the decline in ${pick(policyObjects, i)}.`,
        [`There is several reasons for the decline in ${pick(policyObjects, i)}.`, `There has several reasons for the decline in ${pick(policyObjects, i)}.`, `There are several reason for the decline in ${pick(policyObjects, i)}.`],
        'There are + pluriel',
        'Le nom réel est “reasons”, pluriel. Il faut donc “there are”.', i),
      (i, id) => item(id, 'sentence-parts', 'Choisis la suite logique', 'Structure',
        `To reduce emissions, ${pick(singularActors, i)} ___.`,
        `introduced stricter standards`, ['because stricter standards', 'which stricter standards', 'stricter standards introduced'],
        'Infinitif de but + proposition principale',
        'Après “To reduce emissions”, il faut dire qui fait l’action et ce qui est fait.', i),
      (i, id) => item(id, 'sentence-parts', 'Corrige la phrase', 'Structure',
        `Choose the best correction: “After reviewing the evidence on ${pick(topics, i)}, the decision was changed.”`,
        `After reviewing the evidence on ${pick(topics, i)}, the committee changed the decision.`,
        [`After reviewing the evidence on ${pick(topics, i)}, the decision was changed.`, `After reviewed the evidence on ${pick(topics, i)}, the committee changed the decision.`, `After reviewing the evidence on ${pick(topics, i)}, changing the decision.`],
        'Participe rattaché au bon acteur',
        'La personne ou le groupe qui suit la virgule doit pouvoir faire l’action “reviewing”.', i),
      (i, id) => item(id, 'sentence-parts', 'Choisis la phrase correcte', 'Structure',
        `${cap(pick(topics, i))} ___ a major issue in many cities.`,
        'has become', ['have become', 'having become', 'becoming'],
        'Verbe complet',
        'Il faut un verbe conjugué complet : “has become”.', i),
      (i, id) => item(id, 'sentence-parts', 'Corrige la phrase', 'Ponctuation',
        `Choose the best correction: “The survey on ${pick(topics, i)} was short it still produced useful results.”`,
        `The survey on ${pick(topics, i)} was short, but it still produced useful results.`,
        [`The survey on ${pick(topics, i)} was short it still produced useful results.`, `The survey on ${pick(topics, i)} was short, it still produced useful results.`, `The survey on ${pick(topics, i)} was short but still produced useful results it.`],
        'Deux idées complètes doivent être reliées',
        'Deux propositions complètes ont besoin d’un vrai lien : ici “, but” fonctionne.', i)
    ],

    verbals: [
      (i, id) => item(id, 'verbals', 'Choisis la forme', 'Gérondif',
        `${cap(pick(singularActors, i))} recommended ___ the timetable.`,
        'revising', ['to revise', 'revise', 'revised'],
        'Recommend + -ing',
        'Après “recommend”, on utilise souvent le gérondif : “recommended revising”.', i),
      (i, id) => item(id, 'verbals', 'Choisis la forme', 'Infinitif',
        `The new scheme aims ___ ${pick(policyObjects, i)}.`,
        'to improve', ['improving', 'improve', 'improved'],
        'Aim + to',
        '“Aim” se construit avec “to + base verbale”.', i),
      (i, id) => item(id, 'verbals', 'Complète la phrase', 'Gérondif',
        `${cap(pick(pluralActors, i))} avoided ___ during peak hours.`,
        'travelling', ['to travel', 'travel', 'travelled'],
        'Avoid + -ing',
        'Après “avoid”, on utilise le gérondif : “avoid travelling”.', i),
      (i, id) => item(id, 'verbals', 'Choisis la forme', 'Infinitif',
        `${cap(pick(singularActors, i))} decided ___ the service next year.`,
        'to expand', ['expanding', 'expand', 'expanded'],
        'Decide + to',
        '“Decide” est suivi de “to + base verbale”.', i),
      (i, id) => item(id, 'verbals', 'Complète la phrase', 'Gérondif',
        `${cap(pick(pluralActors, i))} considered ___ the old equipment.`,
        'replacing', ['to replace', 'replace', 'replaced'],
        'Consider + -ing',
        'Après “consider”, on emploie le gérondif : “consider replacing”.', i),
      (i, id) => item(id, 'verbals', 'Choisis la forme', 'Gérondif',
        `${cap(pick(singularActors, i))} suggested ___ the application process.`,
        'simplifying', ['to simplify', 'simplify', 'simplified'],
        'Suggest + -ing',
        '“Suggest” est suivi d’un gérondif ou d’une proposition en “that”, pas directement de “to”.', i),
      (i, id) => item(id, 'verbals', 'Choisis le sens', 'Gérondif ou infinitif',
        `${cap(pick(singularActors, i))} stopped ___ ${pick(['plastic bags', 'paper forms', 'single-use cups', 'printed tickets', 'diesel vehicles', 'coal-based energy', 'manual records', 'old devices', 'free parking', 'disposable packaging'], i)} in 2022.`,
        'producing', ['to produce', 'produce', 'produced'],
        'Stop doing = cesser',
        '“Stop producing” signifie cesser de produire. “Stop to produce” signifie s’arrêter pour produire.', i),
      (i, id) => item(id, 'verbals', 'Choisis la forme', 'Infinitif',
        `The policy allows ${pick(pluralActors, i)} ___ online.`,
        'to apply', ['applying', 'apply', 'applied'],
        'Allow someone to do something',
        'La structure est “allow + personne + to + verbe”.', i),
      (i, id) => item(id, 'verbals', 'Corrige la phrase', 'Structure',
        `Choose the best correction: “Having analysed the results on ${pick(topics, i)}, the conclusion was clear.”`,
        `Having analysed the results on ${pick(topics, i)}, the researchers reached a clear conclusion.`,
        [`Having analysed the results on ${pick(topics, i)}, the conclusion was clear.`, `Having analysing the results on ${pick(topics, i)}, the researchers reached a clear conclusion.`, `Having analysed the results on ${pick(topics, i)}, a conclusion reached the researchers.`],
        'Participe rattaché au bon sujet',
        'Ce sont les chercheurs qui analysent les résultats, donc ils doivent apparaître comme sujet après la virgule.', i)
    ],

    pronouns: [
      (i, id) => item(id, 'pronouns', 'Choisis le pronom relatif', 'Pronom relatif',
        `The proposal on ${pick(topics, i)}, ___ was published last month, attracted criticism.`,
        'which', ['that', 'what', 'who'],
        'Virgule + chose → which',
        'Dans une relative non essentielle après une virgule, on utilise “which”, pas “that”.', i),
      (i, id) => item(id, 'pronouns', 'Choisis le pronom', 'Possession',
        `${cap(pick(pluralActors, i))} ___ first language is not English may need extra support.`,
        'whose', ['who', 'which', 'whom'],
        'Whose exprime la possession',
        '“Whose first language” signifie “dont la première langue”.', i),
      (i, id) => item(id, 'pronouns', 'Complète la phrase', 'Accord',
        `Each participant in the ${pick(topics, i)} survey submitted ___ answer before Friday.`,
        'their', ['his', 'our', 'its'],
        'Singular they',
        'Quand le genre n’est pas précisé, “their” est une solution naturelle et inclusive après “each participant”.', i),
      (i, id) => item(id, 'pronouns', 'Choisis le pronom', 'Deux éléments',
        `Neither of the two options for ${pick(policyObjects, i)} is ideal; ___ solves the problem completely.`,
        'neither', ['both', 'none', 'all'],
        'Neither = aucun des deux',
        'Avec deux options, “neither” est le choix naturel pour dire “ni l’une ni l’autre”.', i),
      (i, id) => item(id, 'pronouns', 'Choisis la forme', 'Réfléchi',
        `${cap(pick(pluralActors, i))} organised the event ___.`,
        'themselves', ['themself', 'theirselves', 'themselfs'],
        'Themselves',
        'Le pronom réfléchi pluriel correct est “themselves”.', i),
      (i, id) => item(id, 'pronouns', 'Choisis le pronom', 'Accord',
        `These measures for ${pick(policyObjects, i)} are expensive, but ___ may reduce long-term costs.`,
        'they', ['it', 'this', 'that'],
        'Pronom pluriel',
        '“Measures” est pluriel, donc le pronom qui le reprend est “they”.', i),
      (i, id) => item(id, 'pronouns', 'Choisis le pronom relatif', 'Personne ou chose',
        `The students ___ completed the ${pick(topics, i)} course received a certificate.`,
        'who', ['which', 'what', 'where'],
        'Who pour les personnes',
        'Pour des personnes, “who” est le relatif naturel en fonction sujet.', i),
      (i, id) => item(id, 'pronouns', 'Clarifie la référence', 'Clarté',
        `Choose the clearest rewrite: “The policy affected the ${pick(topics, i)} sector, but it changed later.”`,
        `The policy affected the ${pick(topics, i)} sector, but the policy changed later.`,
        [`The policy affected the ${pick(topics, i)} sector, but it changed later.`, `It affected the ${pick(topics, i)} sector, but it changed later.`, `The policy affected the ${pick(topics, i)} sector, but this changed later.`],
        'Évite les pronoms ambigus',
        'Quand “it” peut renvoyer à deux noms, répéter le nom est plus clair.', i)
    ],

    sentences: [
      (i, id) => item(id, 'sentences', 'Répare la phrase', 'Ponctuation',
        `Choose the best correction: “The survey on ${pick(topics, i)} ended the team analysed the responses.”`,
        `The survey on ${pick(topics, i)} ended; the team analysed the responses.`,
        [`The survey on ${pick(topics, i)} ended the team analysed the responses.`, `The survey on ${pick(topics, i)} ended, the team analysed the responses.`, `The survey on ${pick(topics, i)} ended because the team analysed.`],
        'Run-on sentence',
        'Deux propositions complètes doivent être séparées correctement : point, point-virgule ou conjonction.', i),
      (i, id) => item(id, 'sentences', 'Répare la phrase', 'Ponctuation',
        `Choose the best correction: “${cap(pick(policyObjects, i))} improved, residents remained dissatisfied.”`,
        `${cap(pick(policyObjects, i))} improved, but residents remained dissatisfied.`,
        [`${cap(pick(policyObjects, i))} improved, residents remained dissatisfied.`, `${cap(pick(policyObjects, i))} improved but residents remained dissatisfied it.`, `${cap(pick(policyObjects, i))} improved residents remained dissatisfied.`],
        'Comma splice',
        'Une virgule seule ne suffit pas entre deux phrases complètes. “, but” donne un lien correct.', i),
      (i, id) => item(id, 'sentences', 'Combine les idées', 'Style',
        `Which version combines the ideas about ${pick(policyObjects, i)} most effectively?`,
        `${cap(pick(policyObjects, i))} improved rapidly, reducing public concern.`,
        [`${cap(pick(policyObjects, i))} improved. It improved rapidly. It reduced public concern.`, `${cap(pick(policyObjects, i))} rapidly. Improved reducing public concern.`, `Reducing public concern and ${pick(policyObjects, i)} improved rapidly.`],
        'Phrase compacte',
        'Le groupe participial “reducing public concern” relie clairement le résultat à l’action.', i),
      (i, id) => item(id, 'sentences', 'Évite le fragment', 'Structure',
        `Choose the complete sentence about ${pick(topics, i)}.`,
        `Because ${pick(topics, i)} became more important, the government changed its priorities.`,
        [`Because ${pick(topics, i)} became more important.`, `Since public concern increased.`, `Although the costs were high.`, `While the evidence remained limited.`],
        'Phrase complète',
        'Une proposition introduite par because/since/although/while doit être reliée à une principale.', i),
      (i, id) => item(id, 'sentences', 'Choisis la ponctuation', 'Ponctuation',
        `${cap(pick(singularActors, i))} introduced new rules ___ some residents opposed them.`,
        'but', ['because', 'although', 'which'],
        'Coordination logique',
        'Deux idées opposées peuvent être reliées avec “but”.', i),
      (i, id) => item(id, 'sentences', 'Corrige la phrase', 'Parallélisme',
        `Choose the best correction: “The plan for ${pick(policyObjects, i)} aims to reduce costs, improving access and it supports local jobs.”`,
        `The plan for ${pick(policyObjects, i)} aims to reduce costs, improve access and support local jobs.`,
        [`The plan for ${pick(policyObjects, i)} aims to reduce costs, improving access and it supports local jobs.`, `The plan for ${pick(policyObjects, i)} aims reducing costs, to improve access and support local jobs.`, `The plan for ${pick(policyObjects, i)} aims to reduce costs, access improving and local jobs support.`],
        'Parallélisme',
        'Dans une liste d’objectifs, garde la même forme verbale : reduce, improve, support.', i),
      (i, id) => item(id, 'sentences', 'Choisis la meilleure phrase', 'Style',
        `Which sentence is clearest about ${pick(policyObjects, i)}?`,
        `${cap(pick(singularActors, i))} reduced fees so that more residents could use the service.`,
        [`${cap(pick(singularActors, i))} reduced fees and more residents could use the service and it was good.`, `Fees were reduced, residents could use the service more.`, `To use the service more residents fees reduced.`],
        'Lien logique clair',
        '“So that” exprime clairement le but : réduire les frais pour permettre l’accès.', i),
      (i, id) => item(id, 'sentences', 'Répare la phrase', 'Structure',
        `Choose the best correction: “Although the ${pick(['scheme', 'programme', 'policy', 'service', 'pilot project', 'training course', 'recycling plan', 'transport reform', 'health campaign', 'housing initiative'], i)} was popular but it was expensive.”`,
        `Although the ${pick(['scheme', 'programme', 'policy', 'service', 'pilot project', 'training course', 'recycling plan', 'transport reform', 'health campaign', 'housing initiative'], i)} was popular, it was expensive.`,
        [`Although the ${pick(['scheme', 'programme', 'policy', 'service', 'pilot project', 'training course', 'recycling plan', 'transport reform', 'health campaign', 'housing initiative'], i)} was popular but it was expensive.`, `Although the ${pick(['scheme', 'programme', 'policy', 'service', 'pilot project', 'training course', 'recycling plan', 'transport reform', 'health campaign', 'housing initiative'], i)} was popular, but it was expensive.`, `The ${pick(['scheme', 'programme', 'policy', 'service', 'pilot project', 'training course', 'recycling plan', 'transport reform', 'health campaign', 'housing initiative'], i)} although was popular but expensive.`],
        'Although suffit',
        'N’utilise pas “although” et “but” ensemble pour relier les mêmes deux idées.', i),
      (i, id) => item(id, 'sentences', 'Choisis la phrase correcte', 'Structure',
        `Which sentence about ${pick(policyObjects, i)} is grammatically complete?`,
        `The report shows that ${pick(policyObjects, i)} has improved.`,
        [`The report shows that ${pick(policyObjects, i)} has improved.`, `The report showing that ${pick(policyObjects, i)} has improved.`, `That ${pick(policyObjects, i)} has improved the report.`, `Shows that ${pick(policyObjects, i)} has improved.`],
        'Verbe principal',
        '“The report shows…” contient un sujet et un verbe principal. Les autres options sont incomplètes ou mal ordonnées.', i)
    ],

    clauses: [
      (i, id) => item(id, 'clauses', 'Choisis le subordonnant', 'Logique',
        `___ ${pick(singularActors, i)} invests now, future costs will be higher.`,
        'Unless', ['Because', 'Although', 'So that'],
        'Unless = if not',
        '“Unless” signifie “si… ne… pas”. La phrase dit que sans investissement, les coûts augmenteront.', i),
      (i, id) => item(id, 'clauses', 'Complète la phrase', 'Contraste',
        `___ the policy on ${pick(topics, i)} was expensive, it produced clear benefits.`,
        'Although', ['Because', 'So that', 'Unless'],
        'Although = contraste',
        '“Although” introduit une opposition entre coût élevé et bénéfices.', i),
      (i, id) => item(id, 'clauses', 'Choisis la proposition', 'Proposition nominale',
        `___ the study on ${pick(topics, i)} reveals is important for future planning.`,
        'What', ['Which', 'That', 'Where'],
        'What + proposition nominale',
        '“What the study reveals” fonctionne comme le sujet de “is important”.', i),
      (i, id) => item(id, 'clauses', 'Choisis le relatif', 'Relative',
        `The report on ${pick(topics, i)} ___ was published yesterday includes new figures.`,
        'that', ['what', 'where', 'who'],
        'That/which pour une chose',
        'Pour une relative essentielle sur une chose, “that” est correct.', i),
      (i, id) => item(id, 'clauses', 'Ponctue la relative', 'Ponctuation',
        `Choose the sentence meaning that all the reports on ${pick(topics, i)} are online.`,
        `The reports on ${pick(topics, i)}, which were published last week, are online.`,
        [`The reports on ${pick(topics, i)} that were published last week are online.`, `The reports on ${pick(topics, i)} which were published last week are online.`, `The reports on ${pick(topics, i)}, that were published last week are online.`],
        'Relative non restrictive',
        'Les virgules indiquent une information ajoutée sur tous les rapports. Après virgule : “which”, pas “that”.', i),
      (i, id) => item(id, 'clauses', 'Évite le fragment', 'Structure',
        `Choose the complete sentence about ${pick(topics, i)}.`,
        `While ${pick(pluralActors, i)} welcomed the change, some costs increased.`,
        [`While ${pick(pluralActors, i)} welcomed the change.`, `Because some costs increased.`, `Although the evidence was limited.`, `If the survey is accurate.`],
        'Proposition dépendante',
        '“While”, “because”, “although” et “if” ne suffisent pas seuls : il faut une principale.', i),
      (i, id) => item(id, 'clauses', 'Choisis le relatif', 'Lieu',
        `The city ___ the ${pick(topics, i)} pilot scheme began has become a model for others.`,
        'where', ['which', 'who', 'what'],
        'Where pour un lieu',
        'Quand l’antécédent est un lieu et que la relative indique l’endroit, “where” est naturel.', i),
      (i, id) => item(id, 'clauses', 'Choisis le lien', 'Temps',
        `___ the new system for ${pick(policyObjects, i)} was introduced, complaints fell sharply.`,
        'After', ['Despite', 'So that', 'Unless'],
        'After + événement',
        '“After” établit clairement l’ordre temporel entre l’introduction du système et la baisse des plaintes.', i)
    ],

    prepositions: [
      (i, id) => item(id, 'prepositions', 'Complète la date', 'Préposition',
        `The regulation came into force ___ ${pick(dates, i)}.`,
        'on', ['in', 'at', 'by'],
        'On + date précise',
        'On utilise “on” avec un jour ou une date précise.', i),
      (i, id) => item(id, 'prepositions', 'Complète la phrase', 'Préposition',
        `The project began ___ ${pick(years, i)}.`,
        'in', ['on', 'at', 'by'],
        'In + année',
        'On utilise “in” avec une année ou un mois.', i),
      (i, id) => item(id, 'prepositions', 'Complète la phrase', 'Préposition',
        `The meeting starts ___ ${pick(times, i)}.`,
        'at', ['in', 'on', 'by'],
        'At + heure',
        'On utilise “at” avec une heure précise : “at 8 a.m.”', i),
      (i, id) => item(id, 'prepositions', 'Choisis la préposition', 'Collocation',
        `The outcome of the ${pick(topics, i)} policy depends ___ public support.`,
        'on', ['of', 'from', 'at'],
        'Depend on',
        'La collocation correcte est “depend on”.', i),
      (i, id) => item(id, 'prepositions', 'Choisis la préposition', 'Collocation',
        `${cap(pick(pluralActors, i))} are interested ___ the new training programme.`,
        'in', ['on', 'at', 'for'],
        'Interested in',
        'On dit “interested in something”.', i),
      (i, id) => item(id, 'prepositions', 'Choisis la préposition', 'Collocation',
        `${cap(pick(singularActors, i))} is responsible ___ maintaining the equipment.`,
        'for', ['of', 'to', 'on'],
        'Responsible for',
        'La collocation correcte est “responsible for”.', i),
      (i, id) => item(id, 'prepositions', 'Complète la phrase', 'Préposition',
        `There was a sharp increase ___ demand for ${pick(policyObjects, i)} after the announcement.`,
        'in', ['on', 'at', 'for'],
        'Increase in',
        'On dit “an increase in demand/prices/sales”.', i),
      (i, id) => item(id, 'prepositions', 'Complète la phrase', 'Préposition',
        `Prices for ${pick(policyObjects, i)} rose ___ ${pick(['8%', '12%', '15%', '21%', '30%'], i)} between 2020 and 2024.`,
        'by', ['with', 'in', 'on'],
        'Rise by + quantité',
        'Pour exprimer l’ampleur du changement, on utilise “by”: “rose by 12%”.', i),
      (i, id) => item(id, 'prepositions', 'Choisis la préposition', 'Deux ou plusieurs',
        `The report on ${pick(topics, i)} compares results ___ two age groups.`,
        'between', ['among', 'inside', 'through'],
        'Between pour deux groupes',
        'Quand il y a deux groupes clairement distincts, “between” est naturel.', i),
      (i, id) => item(id, 'prepositions', 'Choisis la préposition', 'Période',
        `Complaints fell ___ ${pick(months, i)}.`,
        'in', ['on', 'at', 'to'],
        'In + mois',
        'On utilise “in” avec un mois : “in January”.', i)
    ],

    adjectives: [
      (i, id) => item(id, 'adjectives', 'Choisis le comparatif', 'Comparaison',
        `This method for measuring ${pick(topics, i)} is ___ than the previous one.`,
        'more reliable', ['reliabler', 'most reliable', 'more reliabler'],
        'Comparatif des adjectifs longs',
        'Avec un adjectif long comme “reliable”, on utilise “more”, sans ajouter -er.', i),
      (i, id) => item(id, 'adjectives', 'Choisis le participe', 'Adjectif en -ed/-ing',
        `${cap(pick(pluralActors, i))} were ___ by the sudden announcement.`,
        'surprised', ['surprising', 'surprise', 'surprisingly'],
        '-ed pour le ressenti',
        'Les personnes ressentent l’émotion : elles sont “surprised”. La chose est “surprising”.', i),
      (i, id) => item(id, 'adjectives', 'Mets dans l’ordre', 'Ordre',
        `The museum acquired a ___ ${pick(['sculpture', 'vase', 'tablet', 'mask', 'relief'], i)}.`,
        'remarkable ancient stone', ['stone remarkable ancient', 'ancient stone remarkable', 'stone ancient remarkable'],
        'Ordre des adjectifs',
        'L’ordre courant est opinion → âge → matière : “remarkable ancient stone sculpture”.', i),
      (i, id) => item(id, 'adjectives', 'Choisis le mot', 'Quantité',
        `There were ___ complaints after the new system was introduced.`,
        'fewer', ['less', 'much', 'little'],
        'Fewer + pluriel dénombrable',
        '“Complaints” est pluriel et dénombrable. On utilise “fewer”, pas “less”.', i),
      (i, id) => item(id, 'adjectives', 'Choisis la structure', 'Comparaison',
        `The higher the cost, ___ the demand.`,
        'the lower', ['lower', 'the lowest', 'more low'],
        'The + comparatif, the + comparatif',
        'La structure correcte est “the higher…, the lower…”.', i),
      (i, id) => item(id, 'adjectives', 'Choisis la position', 'Adjectif prédicatif',
        `Which sentence is correct?`,
        'The residents were afraid of the change.',
        ['The afraid residents opposed the change.', 'The residents afraid opposed the change.', 'The residents were fear of the change.'],
        'Afraid après un verbe d’état',
        '“Afraid” s’emploie généralement après “be”: “were afraid”.', i)
    ],

    conjunctions: [
      (i, id) => item(id, 'conjunctions', 'Choisis le lien', 'Contraste',
        `___ the policy was unpopular, it reduced costs.`,
        'Although', ['Because', 'So that', 'Unless'],
        'Although = contraste',
        'On oppose l’impopularité de la politique et son effet positif.', i),
      (i, id) => item(id, 'conjunctions', 'Choisis le lien', 'Cause',
        `${cap(pick(pluralActors, i))} supported the plan ___ it created new jobs.`,
        'because', ['although', 'unless', 'whereas'],
        'Because = cause',
        '“Because” introduit la raison du soutien.', i),
      (i, id) => item(id, 'conjunctions', 'Choisis le lien', 'Contraste',
        `Urban areas grew quickly, ___ rural areas lost population.`,
        'whereas', ['because', 'so that', 'unless'],
        'Whereas = contraste',
        '“Whereas” compare deux situations opposées.', i),
      (i, id) => item(id, 'conjunctions', 'Complète la structure', 'Coordination',
        `The programme is useful for ___ students and teachers.`,
        'both', ['either', 'neither', 'whether'],
        'Both…and',
        'La structure est “both A and B”.', i),
      (i, id) => item(id, 'conjunctions', 'Complète la structure', 'Coordination',
        `The scheme is not only cheaper ___ also easier to use.`,
        'but', ['and', 'or', 'so'],
        'Not only…but also',
        'La structure fixe est “not only… but also…”.', i)
    ]
  };

  const generated = [];

  Object.entries(targets).forEach(([category, count]) => {
    const categoryTemplates = templates[category];
    for (let index = 0; index < count; index += 1) {
      const template = categoryTemplates[index % categoryTemplates.length];
      const variant = Math.floor(index / categoryTemplates.length);
      const id = `bulk-${category.replace(/[^a-z0-9]+/g, '-')}-${String(index + 1).padStart(3, '0')}`;
      generated.push(template(variant, id));
    }
  });

  const existingIds = new Set((window.GRAMMAR_QUESTIONS || []).map((question) => question.id));
  window.GRAMMAR_GENERATED_QUESTIONS = generated.filter((question) => !existingIds.has(question.id));
  window.GRAMMAR_QUESTIONS = [...(window.GRAMMAR_QUESTIONS || []), ...window.GRAMMAR_GENERATED_QUESTIONS];
})();
